<?php 
	if (defined('RUNNING_FROM_ROOT')) {
	  $this->plugin('basePath')->setBasePath($this->basePath().'/public');
	}
	echo $this->doctype(); 
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Guessing Game')?>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    </head>
    <body>
  		<div>
		  	<?php echo $this->content; ?>
		</div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
